#!/bin/bash
./home_calc_AT.py SET3_M02.CSV 
./home_calc_AT.py SET3_M03.CSV 
./home_calc_AT.py SET3_M04.CSV 
./home_calc_AT.py SET3_M05.CSV 
./home_calc_AT.py SET3_M06.CSV 
./home_calc_AT.py SET3_M07.CSV 
./home_calc_AT.py SET3_M08.CSV 
./home_calc_AT.py SET3_M09.CSV 
./home_calc_AT.py SET3_M10.CSV 
./home_calc_AT.py SET3_M11.CSV 
./home_calc_AT.py SET3_M12.CSV 
