#!/bin/bash
./uHome_calc_AT.py SET3_M02.CSV 
./uHome_calc_AT.py SET3_M03.CSV 
./uHome_calc_AT.py SET3_M04.CSV 
./uHome_calc_AT.py SET3_M05.CSV 
./uHome_calc_AT.py SET3_M06.CSV 
./uHome_calc_AT.py SET3_M07.CSV 
./uHome_calc_AT.py SET3_M08.CSV 
./uHome_calc_AT.py SET3_M09.CSV 
./uHome_calc_AT.py SET3_M10.CSV 
./uHome_calc_AT.py SET3_M11.CSV 
./uHome_calc_AT.py SET3_M12.CSV 
